import * as XLSX from 'xlsx';
import { DB } from './db';
import { exportProgramToExcel } from './programExporter';
import type { ImportResult, ImportConflict } from '@/types';

const VALID_BLOCK_TYPES = ['normal', 'circuit', 'superset'];

interface ExcelPrograma { nombre: string; descripcion?: string; imagen_url?: string; }
interface ExcelSesion { id_sesion: number | string; numero_sesion: number; nombre_sesion?: string; }
interface ExcelEjercicio {
  id_ejercicio: number | string; nombre: string; musculos?: string; articulaciones?: string;
  descripcion?: string; video_url?: string; video_url_yt?: string;
}
interface ExcelSE {
  id_sesion: number | string; id_ejercicio: number | string; bloque: string; tipo_bloque: string;
  numero_serie: number; orden_ejercicio: number; repeticiones?: string; tiempo?: string;
}

function slugify(text: string): string {
  return text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
}

function parseSheet<T>(wb: XLSX.WorkBook, sheetName: string): T[] {
  const ws = wb.Sheets[sheetName];
  if (!ws) throw new Error(`Hoja "${sheetName}" no encontrada en el archivo Excel`);
  return XLSX.utils.sheet_to_json<T>(ws, { defval: '' });
}

function validateColumns(rows: Record<string, unknown>[], required: string[], sheetName: string): void {
  if (rows.length === 0) return;
  const keys = Object.keys(rows[0]);
  for (const col of required) {
    if (!keys.includes(col)) throw new Error(`Columna obligatoria "${col}" no encontrada en hoja "${sheetName}"`);
  }
}

export async function importProgramFromExcel(
  buffer: Buffer,
  options?: { overwrite?: boolean; newName?: string }
): Promise<ImportResult | ImportConflict> {
  const wb = XLSX.read(buffer, { type: 'buffer' });

  // Parse sheets
  const programaRows = parseSheet<ExcelPrograma>(wb, 'Programa');
  const sesionesRows = parseSheet<ExcelSesion>(wb, 'Sesiones');
  const ejerciciosRows = parseSheet<ExcelEjercicio>(wb, 'Ejercicios');
  const seRows = parseSheet<ExcelSE>(wb, 'Session_Exercises');

  if (programaRows.length === 0) throw new Error('La hoja "Programa" está vacía');

  // Validate columns
  validateColumns(programaRows as unknown as Record<string, unknown>[], ['nombre'], 'Programa');
  validateColumns(sesionesRows as unknown as Record<string, unknown>[], ['id_sesion', 'numero_sesion'], 'Sesiones');
  validateColumns(ejerciciosRows as unknown as Record<string, unknown>[], ['id_ejercicio', 'nombre'], 'Ejercicios');
  validateColumns(seRows as unknown as Record<string, unknown>[], ['id_sesion', 'id_ejercicio', 'bloque', 'tipo_bloque', 'numero_serie', 'orden_ejercicio'], 'Session_Exercises');

  const programName = options?.newName || String(programaRows[0].nombre).trim();
  if (!programName) throw new Error('El nombre del programa es obligatorio');

  // Validate block types and blocks
  for (let i = 0; i < seRows.length; i++) {
    const row = seRows[i];
    const bt = String(row.tipo_bloque).trim().toLowerCase();
    if (!VALID_BLOCK_TYPES.includes(bt)) {
      throw new Error(`Fila ${i + 2} de Session_Exercises: tipo_bloque "${row.tipo_bloque}" no válido. Valores permitidos: normal, circuit, superset`);
    }
    const bloque = String(row.bloque).trim();
    if (!/^[A-Z]$/.test(bloque)) {
      throw new Error(`Fila ${i + 2} de Session_Exercises: bloque "${row.bloque}" no válido. Debe ser una letra mayúscula (A-Z)`);
    }
  }

  // Validate cross-references
  const excelExIds = new Set(ejerciciosRows.map(e => String(e.id_ejercicio)));
  const excelSesIds = new Set(sesionesRows.map(s => String(s.id_sesion)));
  for (let i = 0; i < seRows.length; i++) {
    const row = seRows[i];
    if (!excelExIds.has(String(row.id_ejercicio))) {
      throw new Error(`Fila ${i + 2} de Session_Exercises: id_ejercicio "${row.id_ejercicio}" no existe en hoja Ejercicios`);
    }
    if (!excelSesIds.has(String(row.id_sesion))) {
      throw new Error(`Fila ${i + 2} de Session_Exercises: id_sesion "${row.id_sesion}" no existe en hoja Sesiones`);
    }
  }

  // Check name conflict
  const existing = await DB.get<{ id: number; name: string }>('SELECT id, name FROM programs WHERE name = ?', [programName]);
  if (existing && !options?.overwrite) {
    return { conflict: true, existingId: existing.id, existingName: existing.name };
  }

  // If overwrite, delete existing program (backup should have been generated by caller)
  if (existing && options?.overwrite) {
    const existingSessions = await DB.query<{ id: number }>('SELECT id FROM sessions WHERE program_id = ?', [existing.id]);
    const sesIds = existingSessions.map(s => s.id);
    if (sesIds.length) {
      await DB.run(`DELETE FROM session_exercises WHERE session_id IN (${sesIds.map(() => '?').join(',')})`, sesIds);
    }
    await DB.run('DELETE FROM sessions WHERE program_id = ?', [existing.id]);
    await DB.run('DELETE FROM programs WHERE id = ?', [existing.id]);
  }

  // Resolve exercises: create new ones, map excel id → db id
  const excelIdToDbId = new Map<string, number>();
  let exercisesCreated = 0;
  for (const ex of ejerciciosRows) {
    const exName = String(ex.nombre).trim();
    if (!exName) continue;
    const dbEx = await DB.get<{ id: number }>('SELECT id FROM exercises WHERE name = ?', [exName]);
    if (dbEx) {
      excelIdToDbId.set(String(ex.id_ejercicio), dbEx.id);
    } else {
      const result = await DB.run(
        'INSERT INTO exercises (name, muscles, joints, description, video_url, video_url_yt) VALUES (?,?,?,?,?,?)',
        [exName, ex.musculos || null, ex.articulaciones || null, ex.descripcion || null, ex.video_url || null, ex.video_url_yt || null]
      );
      excelIdToDbId.set(String(ex.id_ejercicio), result.id);
      exercisesCreated++;
    }
  }

  // Create program
  const slug = slugify(programName);
  const progResult = await DB.run(
    'INSERT INTO programs (name, description, image_url) VALUES (?,?,?)',
    [programName, programaRows[0].descripcion || null, programaRows[0].imagen_url || null]
  );
  const programId = progResult.id;

  // Create sessions and map excel session id → db session id
  const excelSesIdToDbId = new Map<string, number>();
  for (const ses of sesionesRows) {
    const num = Number(ses.numero_sesion) || 1;
    let sessionCode = `${slug}_s${num}`;
    // Ensure uniqueness
    const existing = await DB.get('SELECT id FROM sessions WHERE session_code = ?', [sessionCode]);
    if (existing) sessionCode = `${slug}_s${num}_${programId}`;
    const sesResult = await DB.run(
      'INSERT INTO sessions (session_code, name, program_id) VALUES (?,?,?)',
      [sessionCode, ses.nombre_sesion || null, programId]
    );
    excelSesIdToDbId.set(String(ses.id_sesion), sesResult.id);
  }

  // Create session_exercises
  for (const se of seRows) {
    const dbSessionId = excelSesIdToDbId.get(String(se.id_sesion));
    const dbExId = excelIdToDbId.get(String(se.id_ejercicio));
    if (!dbSessionId || !dbExId) continue;
    await DB.run(
      'INSERT INTO session_exercises (session_id, block, block_type, set_number, ex_id, ex_order, reps, tiempo_ej) VALUES (?,?,?,?,?,?,?,?)',
      [dbSessionId, se.bloque || null, String(se.tipo_bloque).toLowerCase() || 'normal',
       Number(se.numero_serie) || 1, dbExId, Number(se.orden_ejercicio) || 1,
       se.repeticiones || null, se.tiempo || null]
    );
  }

  return { programId, sessionsCreated: sesionesRows.length, exercisesCreated };
}

export async function generateBackupExcel(programId: number): Promise<Buffer> {
  return exportProgramToExcel(programId);
}
